data_dir: "/commons/Themas/Thema07/metagenomics/zoutstress/"

kaiju_index_fmi: "/students/2024-2025/Thema07/metagenomics/zoutstress/kaiju_index/kaiju_db_fungi/kaiju_db_fungi.fmi"
kaiju_index_nodes: "/students/2024-2025/Thema07/metagenomics/zoutstress/kaiju_index/kaiju_db_fungi/nodes.dmp"

sample_dirs:
  - "16S/zoet_20_30cm_rep1/"
  - "16S/zoet_20_30cm_rep2/"
  - "16S/zout_20_30cm_rep1/"
  - "16S/zout_20_30cm_rep2/"
  - "WGS/zoet_20_30cm_rep1/"
  - "WGS/zoet_20_30cm_rep2/"
  - "WGS/zout_20_30cm_rep1/"
  - "WGS/zout_20_30cm_rep2/"

threads: 10
