data_dir: "/commons/Themas/Thema07/metagenomics/zoutstress/"

kaiju_bin: "/students/2024-2025/Thema07/metagenomics/zoutstress/tools/kaiju/bin
kaiju_index_fmi: "/students/2024-2025/Thema07/metagenomics/zoutstress/kaiju_index/kaiju_db_fungi/kaiju_db_fungi.fmi"
kaiju_index_nodes: "/students/2024-2025/Thema07/metagenomics/zoutstress/kaiju_index/kaiju_db_fungi/nodes.dmp"

seq_dirs:
  - "16S/"
  - "WGS/"

sample_groups:
  - "zoet_20_30cm_rep1/"
  - "zoet_20_30cm_rep2/"
  - "zout_20_30cm_rep1/"
  - "zout_20_30cm_rep2/"

threads: 10
